### ISSUE TITLE
right associative

### ISSUE THREAD

**Issue by RonaldBilbit** [MostAwesomeDude/brismu#2]
Hi,

why Lojban is "right associative" ?

```
$ echo "ganai broda gi ganai brode gi broda" |jbofihe
(0[{ga nai} broda gi {<ga nai> brode gi broda}])0

```

`ax-k $a |- ganai broda gi ganai brode gi broda $.
`

**Comment by MostAwesomeDude** [comment]
Hi! This is a great question which extends back to [Loglan](https://en.wikipedia.org/wiki/Loglan), the predecessor to Lojban. From the Lojban perspective, there are two ways to create a logical connection between utterances, known as **forethought** and **afterthought**. A forethought connector like {ganai} is used when the speaker knows how they will connect their *bridi*, or its afterthought counterparts {nagi'a}, {na.a}, or {naja} can be used when the speaker has already uttered their *bridi* and wish to append an additional clause.

I don't know the full answer to your question and I hope that others add their opinions, notes, and references. However, there's an obvious grammatical reason to make forethought connectors associate "to the right": it allows the speaker to *finish uttering* the connector and first subordinate *bridi* before worrying about the internal grammar of the second subordinate *bridi*.

In *la brismu*, we use {ganai} for the initial axioms because it has the simplest grammar; {ganai} takes *bridi* and produces *bridi*. This grammar happens to require an association to the right. We can still express any nesting we like; see [ax-s](https://brismu.systems/ax-s.html) for an example of both groupings, starting with {ganai ganai}.

**Comment by RonaldBilbit** [comment]
Hi,

> However, there's an obvious grammatical reason to make forethought connectors associate "to the right": it allows the speaker to finish uttering the connector and first subordinate bridi before worrying about the internal grammar of the second subordinate bridi.

Ok. So this is not an explicit rule that I will find in "The Complete Lojban Language", but an implicit rule.

In Metamath : metamath is implicitly right-associative. See. https://us.metamath.org/mpeuni/wi.html
but in https://us.metamath.org/mpeuni/ax-1.html, the rule is recalled by the use of parentheses.

> ax-1	⊢ (𝜑 → (𝜓 → 𝜑))


I Metamath Zero: The rule is explicit: 

```
nonempty sort wff;
var ph ps ch: wff*;
term wi (ph ps: wff): wff; infixr wi: -> 25;

```

Do you think the point of view I express here is correct ?

Source 
https://groups.google.com/g/metamath/c/raGj9fO6U2I/m/BmLGM6xoCgAJ
https://math.stackexchange.com/questions/2829703/left-or-right-connective-associativity
https://digama0.github.io/mm0/thesis.pdf
